<?php
function custom_view_modes_help($path, $arg) {
    switch ($path) {
    case "admin/help#media_view_modes":
        return '<p>'. t("Creates additional view modes for Media and Nodes.") .'</p>';
        break;
    }
}
 
function custom_view_modes_theme() {
    return array(
                 'media_view_modes_javascript' => array(
                                                   'arguments' => array(),
                                                   ),
                 );   
}


//Add more view modes for Media formatting. 
function custom_view_modes_entity_info_alter(&$entity_info) {

  //Not sure if it's still an issue, but a previous commenter noted that Media module only recognizes view modes with the prefix media_. Also, as you can see by the entity type 'file', this is for after the switch-to-file-entity patch.
  $entity_info['file']['view modes']['slide_show'] = array(
    'label' => t('Slide Show'),
    'custom settings' => TRUE
  );
  $entity_info['node']['view modes']['slide_show'] = array(
      'label' => t('Slide Show'),
      'custom settings' => TRUE
  );
  $entity_info['file']['view modes']['popup'] = array(
    'label' => t('Popup'),
    'custom settings' => TRUE
  );
  $entity_info['node']['view modes']['popup'] = array(
      'label' => t('Popup'),
      'custom settings' => TRUE
  );
 
}

/**
* Implements hook_preprocess_node().
*/
function custom_view_modes_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'teaser') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__teaser';
  }
  if($vars['view_mode'] == 'slide_show') {
      $vars['theme_hook_suggestions'][] = 'node__'. $vars['type'] .'__front_slide_show';
  }
  if($vars['view_mode'] == 'popup') {
      $vars['theme_hook_suggestions'][] = 'node__'. $vars['type'] .'__popup';
  }
}
